cask 'antigravity'
cask 'claude-code'
cask 'discord'
cask 'docker'
cask 'flycut'
cask 'font-jetbrains-mono' # For use in Zed etc. Ghostty bundles this, so it might not actually be used/needed
cask 'ghostty'
cask 'google-drive'
cask 'google-chrome'
cask 'ollama'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'zed'

# Modern shell tools
brew 'starship'           # Modern cross-shell prompt
brew 'fzf'                # Fuzzy finder
brew 'eza'                # Modern ls replacement
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'zsh-history-substring-search'

# Development tools
brew 'oven-sh/bun/bun'
brew 'chruby'
brew 'direnv'
brew 'duti'
brew 'exercism'
brew 'fswatch'
brew 'gh'
brew 'go'
brew 'withgraphite/tap/graphite'
brew 'jq'
brew 'just'
brew 'nvm'
brew 'postgresql@14', restart_service: true
brew 'pstree'
brew 'python'
brew 'rsync'
brew 'ruby-install'
brew 'stow'
brew 'telnet'
brew 'the_platinum_searcher'
brew 'tmux'
brew 'tree'
brew 'uv'
brew 'watch'
brew 'wget'
